### ISSUE TITLE
SELECT FROM

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#10]
When cols are empty we are not adding `*` . Does that helps to resolve the error in query ? ( `SELECT FROM` )
Line 119 adding an else does that fix the issue ?

```
    // add columns
    if ($this->cols) {
        $text .= $line . implode($csep, $this->cols) . PHP_EOL;
    } else {
        $text .= ' * ' . PHP_EOL;
    }
```

**Comment by pmjones** [comment]
So the issue is, if somebody does this ...

```
$select->from('table_name');
$result = $sql->query($select);
```

... then it fails, because they didn't specify any cols to retrieve.

Although it seems harmless, I don't think we should set a default for that.  My fear is that it could get in the way of some kinds of rare but necessary queries, but I don't have any proof for that.

We can point out in the documentation how to debug that kind of problem, though.  Would that help?

**Comment by harikt** [comment]
Can we throw an exception stating the reason, when cols is empty ?

**Comment by pmjones** [comment]
I get the idea there may be times when cols is _supposed_ to be empty, but I don't know.  Is the error not obvious when it occurs?

**Comment by harikt** [comment]
@pmjones I will check . Before this I am testing the closed issues which seems not really resolved. I will open it .

**Comment by harikt** [comment]
This was what I was trying earlier 

```
$select = new Aura\Sql\Select($sql);
$select->from('posts');
$result = $sql->fetchOne($select);
var_export($result);
```

When column is not given error is 

```
SELECT
PHP Fatal error:  Uncaught exception 'Aura\Autoload\Exception\NotReadable' with message 'Aura\Sql\Select
#0: /media/Linux/aurasystem/package/Aura.Sql/src
#1.:/usr/share/php:/usr/share/pear' in /media/Linux/aurasystem/package/Aura.Autoload/src/Aura/Autoload/Loader.php:317
Stack trace:
#0 [internal function]: Aura\Autoload\Loader->load('Aura\Sql\Select')
#1 /media/Linux/auracomponentstest/select.php(26): spl_autoload_call('Aura\Sql\Select')
#2 {main}
  thrown in /media/Linux/aurasystem/package/Aura.Autoload/src/Aura/Autoload/Loader.php on line 317
```

Obviously nothing there to figure out right ?

When table name is not given , error below 

```
$select = new Aura\Sql\Select($sql);
$select->cols(array('id', 'author_id', 'title', 'body'));
$result = $sql->fetchOne($select);
var_export($result);
```

Which I got the errors as below 

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'' in /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Profiler.php:82
Stack trace:
#0 /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Profiler.php(82): PDOStatement->execute()
#1 /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Adapter/AbstractAdapter.php(282): Aura\Sql\Profiler->exec(Object(PDOStatement), Array)
#2 /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Adapter/AbstractAdapter.php(547): Aura\Sql\Adapter\AbstractAdapter->query(Object(Aura\Sql\Select), Array)
#3 /media/Linux/auracomponentstest/select.php(29): Aura\Sql\Adapter\AbstractAdapter->fetchOne(Object(Aura\Sql\Select))
#4 {main}
  thrown in /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Profiler.php on line 82

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'' in /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Profiler.php:82
Stack trace:
#0 /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Profiler.php(82): PDOStatement->execute()
#1 /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Adapter/AbstractAdapter.php(282): Aura\Sql\Profiler->exec(Object(PDOStatement), Array)
#2 /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Adapter/AbstractAdapter.php(547): Aura\Sql\Adapter\AbstractAdapter->query(Object(Aura\Sql\Select), Array)
#3 /media/Linux/auracomponentstest/select.php(29): Aura\Sql\Adapter\AbstractAdapter->fetchOne(Object(Aura\Sql\Select))
#4 {main}
  thrown in /media/Linux/aurasystem/package/Aura.Sql/src/Aura/Sql/Profiler.php on line 8
```

**Comment by harikt** [comment]
I have modified the comments with the latest errors thrown.

**Comment by pmjones** [comment]
I don't think this is that big a deal, but even so, what do you suggest as the remedy?

**Comment by harikt** [comment]
What my suggestion is if no fields or table name found lets throw a meaningful exception

**Comment by pmjones** [comment]
Technically, you don't always need a table name.  For example, you can issue `SELECT NOW()` and it works just fine.

After thinking about this for a long time, I realize I'd rather not get into checking SQL syntax in the PHP; if the developer gets it wrong, he'll be notified by the database. PDO will throw an exception with everything you need to diagnose the failure.

**Comment by harikt** [comment]
ok :)
